services:
  - docker

language: java
sudo: false # faster builds

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - docker login registry.cn-hangzhou.aliyuncs.com -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/work  -it  maven:3-openjdk-11 bash /work/build.sh

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - echo "build succeed"

after_failure:
  - echo "build failed!"
