services:
  - docker

language: java
sudo: false # faster builds

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - docker login registry.cn-hangzhou.aliyuncs.com -u $DOCKER_USER -p $DOCKER_PASSWORD
  - mvn install -Dmaven.test.skip=true -B

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - echo "build succeed"

after_failure:
  - echo "build failed!"
