services:
  - docker

language: java

sudo: false # faster builds

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

before_script:
  - sed -i "s/{{DOCKER_USER}}/$DOCKER_USER/g" mvn-setting-template.xml
  - sed -i "s/{{DOCKER_PASSWORD}}/$DOCKER_PASSWORD/g" mvn-setting-template.xml
  - cp -rf mvn-setting-template.xml $HOME/.m2/

script:
  - mvn install -Dmaven.test.skip=true -B

after_success:
#  - bash <(curl -s https://codecov.io/bash)
  - echo "build succeed"

after_failure:
  - echo "build failed!"
