version: "3"

services:

  registry:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.registry:1.0.0-SNAPSHOT
    environment:
      - PARAMS
    networks:
      - toolbox
    ports:
      - 29000:29000

  gateway:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.gateway:1.0.0-SNAPSHOT
    environment:
      - PARAMS
    ports:
      - 28888:28888
    networks:
      - toolbox

  mysql:
    restart: always
    image: mysql:8
    networks:
      - toolbox
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  dbbackup:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.dbbackup:1.0.0-SNAPSHOT
    networks:
      - toolbox
    environment:
      - MYSQL_ROOT_PASSWORD
    depends_on:
      - mysql
    volumes:
      - ./data/dbbackup:/backup

  auth:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.auth:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  spider:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.spider:1.0.0-SNAPSHOT
    networks:
      - toolbox

  goods:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.goods:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  logistics:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.logistics:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  order:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.order:1.0.0-SNAPSHOT
    networks:
      - toolbox
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - PARAMS

  web:
    restart: always
    image: registry.cn-hangzhou.aliyuncs.com/lzk90s/com.github.lzk90s.fttb.web:1.0.0-SNAPSHOT
    networks:
      - toolbox
    ports:
      - 20080:80

networks:
  toolbox:
    driver: bridge
