server:
  port: 22334

spring:
  application:
    name: goods
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql:3306/goods?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

logistics:
  yw56:
    enable: true
    vendor: 燕文物流

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/gateway/routes
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://registry:29000/eureka/

security:
  oauth2:
    resource:
      loadBalanced: true
      prefer-token-info: false
      user-info-uri: http://auth/user

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    logic-not-delete-value: 0
    field-strategy: 2
    logic-delete-value: -1
    db-column-underline: true
    refresh-mapper: true
    id-type: 0