spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:29000/eureka/

SPIDER_HOST: http://localhost:33023