spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trade?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456

logistics:
  yw56:
    enable: true
    priceUrl: https://price.yw56.com.cn/busHalOnline/getChargePriceExt.htm
    userId: 100000
    apkToken: D6140AA383FD8515B09028C586493DDB

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:29000/eureka/